### PR TITLE
upgrade to django 1.9 the models by renaming fields in concrete entities

### PR DESCRIPTION
**Pull request by escanda**
This may alleviate Xavi's work on upgrading to Django 1.9. Needs to be more thoroughly tested but works as is. Remember to migrate before testing :)

### CODE REVIEW

**Comment by XaviP** [comment]
thanks @escanda !! I'll be testing these days, coordinated with @bum2

**Comment by bum2** [comment]
I'm having problems trying to merge this pull request in local, with the error:
`django.db.utils.IntegrityError: NOT NULL constraint failed: general_address_type__new.space_type_ptr_id`

seems like more changes are needed... i'll investigate this as soon as i can (perhaps tuesday)

**Comment by escanda** [comment]
I am testing with `migrate` after inserting the .sql files in the project's root and cannot reproduce the issue. Which steps may I follow?

**Comment by bum2** [comment]
i have updated 3 sqls....

**Pull request merged**
