### PR TITLE
Update models.py

### PR DESCRIPTION
**Pull request by skoria**
corrected according to https://titanpad.com/freedomcoopmemberform

### CODE REVIEW

**Comment by bhaugen** [comment]
Git workflow question: who should be responsible for merging pull requests? This appears to be contain only help text changes and so should not have any bug-causing tendencies: in other words, it is pretty safe. And apparently the changes have been discussed and this is just to implement agreed changes. So it should be merged.

I can do it,  but want to raise the question of how we should handle merge requests. I don't want to be making executive decisions for this project.

**Comment by bhaugen** [comment]
Also, I am very glad to see yet another participant in working on the code. Thanks a lot, @skoria !

**Comment by bhaugen** [comment]
I think it would be best for @XaviP to merge the pull requests, he would be the person to deploy them and is closer to the action and collective decisions than me and Lynn.

**Comment by bum2** [comment]
for me is great the commit! i think we will need to create and apply migrations anyway...

**Comment by bhaugen** [comment]
I'm not sure changes to help text require migrations. They might. They did not in the older South migrations,, but the new Django ones are often fussier.

**Comment by XaviP** [comment]
Yes, changes in help text generate new migration file when makemigrations.

**Comment by bhaugen** [comment]
They certainly do. I don't think South used to do that, but I suspect it has to do with keeping the sequence of migrations accurate.

**Pull request merged**
