### PR TITLE
Change test membership request to expect account login rather than pr…

### PR DESCRIPTION
**Pull request by cillian**
…oject login page.

The account login template was being in loaded in this test rather then the project login template here. Possibly because there is no /freedom-coop project in the test db? So not sure if this is an appropriate fix, maybe the test should be changed so the project login template is actually loaded.

### CODE REVIEW

**Comment by bhaugen** [comment]
@cillian your fix seems to have solved one error, but the selenium installation problem remains in the first travis build. I don't know enough about travis or selenium to understand why.

And I don't think it is worth fixing.

I think we should get rid of all the selenium tests and the selenium dependencies (which means either delete or comment-out this test file completely). They were added by a dev who is gone, and I don't think anybody else wants to maintain them. There are much simpler ways to do interactive template testing in django than using selenium (eg django-webtest). And this set of tests is relatively trivial anyway, So I think I would just get rid of this test. 

@fosterlynn @bum2 do you disagree?

**Comment by fosterlynn** [comment]
>@fosterlynn @bum2 do you disagree?

I don't know enough about it to agree or disagree, I leave it to you all.

**Comment by bhaugen** [comment]
Disabling that test and selenium would not be a drastic change. Selenium is just used in this one test file. (And mentioned in requirements.txt and tox.ini).

**Comment by XaviP** [comment]
I think you can change the version of selenium in requeriments.txt, selenium 3.5.0 was working ok for me. Newer versions of selenium doesn't support phantom.js:
```
UserWarning: Selenium support for PhantomJS has been deprecated, please use headless versions of Chrome or Firefox instead
```
Another approach is to change to a new driver like chromedriver instead of phantom.js
https://sites.google.com/a/chromium.org/chromedriver/downloads

Hope it helps!

**Comment by bhaugen** [comment]
@XaviP thank you very much!

@cillian he is the person who understands selenium. I would take his advice more than mine,

**Comment by XaviP** [comment]
Hey, I've made a quick test with selenium=3.5.0 but it seems it doesn't work neither :-( Probably someone has made changes in code (templates?) without taking care of the test.
If nobody is gonna take care of it, I think Bob's proposal is a better approach.

**Comment by bhaugen** [comment]
@XaviP thanks again. @cillian if you still want to pursue the selenium problem, I'll check out the templates.

**Comment by cillian** [comment]
thanks @XaviP chromedriver worked well.

@bhaugen I disabled the admin parts of these tests for now because there doesn't appear to be a freedom-coop project in /work/tests/objects_for_work_tests.py , the test reaches a page with "No Project matches given query".

**Comment by bhaugen** [comment]
Thanks a lot @cillian and @XaviP ! It's a relief to have the travis tests pass again! Not good to ignore them if they are  broken, which has been the case for awhile. This is a big improvement!

I'll think about whether to add the freedom-coop project to the test objects. I got rid of all those hard-coded named objects in the LearnDeep fork, but Fair Coop needs some designated objects. Would be good to put them in some user-defined data so they are no longer hard coded. But that's for another time...

**Pull request merged**
