### PR TITLE
Electrum to daemon

### PR DESCRIPTION
**Pull request by XaviP**
Hi, I open the pull request to comment some changes in creating a dev enviroment. 
Please see [install doc](https://github.com/FreedomCoop/valuenetwork/blob/electrum_to_daemon/docs/install_ocp_debian_apache_ssl.rst) to understand that daemon is running in the system python interpreter and django is running in virtualenv python interpreter, so both processes are running independently, communicating by json.
We can explore bugs here and wait for a more stable electrum_to_daemon branch, or merge with master and solve any bugs there, as you prefer.

### CODE REVIEW

**Comment by XaviP** [comment]
These are the issues to solve:
- The daemon when stops (or reload) keeps the port busy, so not possible to start again with the same port.
- In daemon.py cmd_wallet object is missing, but some functions use it.
- The address balance is not working in ocp (manage account) Tested with an address with 1 faircoin, it's not shown in ocp.

**Comment by XaviP** [comment]
This is the dev state: many issues solved, now it seems ocp code is working ok, but we need to solve one issue in daemon (NotEnoughFunds when making a transaction)

**Comment by XaviP** [comment]
I think this branch is mature enough to merge into master. It seems the merge has no conflicts.

**Comment by bhaugen** [comment]
Do it.

**Pull request merged**
